services:
  nameserver:
    build:
      context: .
      dockerfile: deploy/nameserver/Dockerfile
    container_name: nameserver
    command: ["--addr", "8080"]
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    ports:
      - protocol: tcp
        target: 8080
        published: 8080

  datanode1:
    depends_on: ["nameserver"]
    build:
      context: .
      dockerfile: deploy/datanode/Dockerfile
    container_name: datanode-1
    command: ["--config", "/var/lib/datanode/config.yaml"]
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    ports:
      - protocol: tcp
        target: 8080
        published: 8081
    stop_grace_period: "10s"
    volumes:
      - type: bind
        source: .data/1.yaml
        target: /var/lib/datanode/config.yaml
