services:
  namenode1:
    depends_on: ["redis"]
    build:
      context: .
      dockerfile: deploy/namenode/Dockerfile
    container_name: namenode
    command:
      - "--addr=8080"
      - "--redis=redis:6379"
      - "--db=1"
      - "--master"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    ports:
      - protocol: tcp
        target: 8080
        published: 8080

  datanode1:
    depends_on: ["namenode1"]
    build:
      context: .
      dockerfile: deploy/datanode/Dockerfile
    container_name: datanode-1
    command:
      - "--addr=8080"
      - "--redis=redis:6379"
      - "--db=1"
      - "--host=datanode1"
      - "--base=/var/lib/datanode"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    ports:
      - protocol: tcp
        target: 8080
        published: 8081
    stop_grace_period: "5s"
    volumes:
      - type: volume
        source: datanode1
        target: /var/lib/datanode/

  datanode2:
    depends_on: ["namenode1"]
    build:
      context: .
      dockerfile: deploy/datanode/Dockerfile
    container_name: datanode-2
    command:
      - "--addr=8080"
      - "--redis=redis:6379"
      - "--db=1"
      - "--host=datanode2"
      - "--base=/var/lib/datanode"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    ports:
      - protocol: tcp
        target: 8080
        published: 8082
    stop_grace_period: "5s"
    volumes:
      - type: volume
        source: datanode2
        target: /var/lib/datanode/

  datanode3:
    depends_on: ["namenode1"]
    build:
      context: .
      dockerfile: deploy/datanode/Dockerfile
    container_name: datanode-3
    command:
      - "--addr=8080"
      - "--redis=redis:6379"
      - "--db=1"
      - "--host=datanode3"
      - "--base=/var/lib/datanode"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    ports:
      - protocol: tcp
        target: 8080
        published: 8083
    stop_grace_period: "5s"
    volumes:
      - type: volume
        source: datanode3
        target: /var/lib/datanode/

  redis:
    image: redis:7.0
    container_name: redis
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2"
          memory: "0.5G"
    ports:
      - protocol: tcp
        target: 6379
        published: 6379
    environment:
      TZ: Asia/Seoul

volumes:
  datanode1:
    name: datanode1
  datanode2:
    name: datanode2
  datanode3:
    name: datanode3
